feat: implement contract hash
jstz-dev/jstz pull request #725
Opened 2024-12-31 16:17 UTC by ryutamago

# Context

[Introduce smart function hash](https://linear.app/tezos/issue/JSTZ-251/introduce-smartfunctionhash)

In preparation for [254](https://linear.app/tezos/issue/JSTZ-254/migrate-to-newaddress-type)

# Description

1. Introduce a `JstzHash` trait 
```
pub trait JstzHash<'de>:
    Sized
    + ...
{
    fn to_base58(&self) -> String;

    fn from_base58(data: &str) -> Result<Self>;

    fn as_bytes(&self) -> &[u8];

    fn digest(data: &[u8]) -> Result<Self>;
}
```
2. make `PublicKeyHash` implement the JstzHash

3. Introduce `SmartFunctionHash` that implements the JstzHash. this hash will be used for sf address and starts with `TZ1...`

# Manually testing the PR

unit test

2025-01-02 10:28 UTC, huancheng-trili commented on crates/jstz_core/src/kv/outbox.rs
> +        let digest = PublicKeyHash::digest(b"account1");
It seems that these lines don't need to be changed?

2025-01-02 11:31 UTC, ryutamago commented on crates/jstz_core/src/kv/outbox.rs
> +        let digest = PublicKeyHash::digest(b"account1");
fixed!

2025-01-02 17:03 UTC, huancheng-trili approved these changes
Just one comment

2025-01-03 09:30 UTC, huancheng-trili approved these changes

2025-01-03 09:32 UTC, huancheng-trili requested changes
Wait why's the new commit including changes out of scope?

2025-01-03 09:35 UTC, huancheng-trili approved these changes
sorry false alert

2025-01-03 09:53 UTC, merged